CREATE DATABASE IF NOT EXISTS db_1;
USE db_1;
CREATE TABLE IF NOT EXISTS tabla_usuarios(
    `id_usuario` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `nombres_usuario` VARCHAR(16) NOT NULL
) ENGINE = InnoDB;
CREATE DATABASE IF NOT EXISTS db_2;
USE db_2;
CREATE TABLE IF NOT EXISTS tabla_usuarios(
    `id_usuario` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `nombres_usuario` VARCHAR(16) NOT NULL
) ENGINE = InnoDB;
CREATE DATABASE IF NOT EXISTS db_3;
USE db_3;
CREATE TABLE IF NOT EXISTS tabla_usuarios(
    `id_usuario` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `nombres_usuario` VARCHAR(16) NOT NULL
) ENGINE = InnoDB;
